#pragma once

#include "common.h"

namespace daniel
{

namespace HID
{

namespace DesktopProfile
{

enum class KeyPage : uint8_t
{
	None              = 0x00 ,
	ErrorRollOver     = 0x01 ,
	POSTFail          = 0x02 ,
	ErrorUndefined    = 0x03 ,
	A                 = 0x04 ,
	a                 = 0x04 ,
	B                 = 0x05 ,
	b                 = 0x05 ,
	C                 = 0x06 ,
	c                 = 0x06 ,
	D                 = 0x07 ,
	d                 = 0x07 ,
	E                 = 0x08 ,
	e                 = 0x08 ,
	F                 = 0x09 ,
	f                 = 0x09 ,
	G                 = 0x0A ,
	g                 = 0x0A ,
	H                 = 0x0B ,
	h                 = 0x0B ,
	I                 = 0x0C ,
	i                 = 0x0C ,
	J                 = 0x0D ,
	j                 = 0x0D ,
	K                 = 0x0E ,
	k                 = 0x0E ,
	L                 = 0x0F ,
	l                 = 0x0F ,
	M                 = 0x10 ,
	m                 = 0x10 ,
	N                 = 0x11 ,
	n                 = 0x11 ,
	O                 = 0x12 ,
	o                 = 0x12 ,
	P                 = 0x13 ,
	p                 = 0x13 ,
	Q                 = 0x14 ,
	q                 = 0x14 ,
	R                 = 0x15 ,
	r                 = 0x15 ,
	S                 = 0x16 ,
	s                 = 0x16 ,
	T                 = 0x17 ,
	t                 = 0x17 ,
	U                 = 0x18 ,
	u                 = 0x18 ,
	V                 = 0x19 ,
	v                 = 0x19 ,
	W                 = 0x1A ,
	w                 = 0x1A ,
	X                 = 0x1B ,
	x                 = 0x1B ,
	Y                 = 0x1C ,
	y                 = 0x1C ,
	Z                 = 0x1D ,
	z                 = 0x1D ,
	N1                = 0x1E ,
	N2                = 0x1F ,
	N3                = 0x20 ,
	N4                = 0x21 ,
	N5                = 0x22 ,
	N6                = 0x23 ,
	N7                = 0x24 ,
	N8                = 0x25 ,
	N9                = 0x26 ,
	N0                = 0x27 ,
	Enter             = 0x28 ,
	Escape            = 0x29 ,
	BackSpace         = 0x2A ,
	Tab               = 0x2B ,
	Space             = 0x2C ,
	Minus             = 0x2D ,
	Equal             = 0x2E ,
	LeftBracket       = 0x2F ,
	RightBracket      = 0x30 ,
	BackSlash         = 0x31 ,
	Tilt              = 0x32 ,
	SemiColon         = 0x33 ,
	Quote             = 0x34 ,
	GraveAccent       = 0x35 ,
	Comma             = 0x36 ,
	Point             = 0x37 ,
	Slash             = 0x38 ,
	CapsLock          = 0x39 ,
	F1                = 0x3A ,
	F2                = 0x3B ,
	F3                = 0x3C ,
	F4                = 0x3D ,
	F5                = 0x3E ,
	F6                = 0x3F ,
	F7                = 0x40 ,
	F8                = 0x41 ,
	F9                = 0x42 ,
	F10               = 0x43 ,
	F11               = 0x44 ,
	F12               = 0x45 ,
	PrintScreen       = 0x46 ,
	ScrollLock        = 0x47 ,
	Pause             = 0x48 ,
	Insert            = 0x49 ,
	Home              = 0x4A ,
	PageUp            = 0x4B ,
	DeleteForward     = 0x4C ,
	End               = 0x4D ,
	PageDown          = 0x4E ,
	RightArrow        = 0x4F ,
	LeftArrow         = 0x50 ,
	DownArrow         = 0x51 ,
	UpArrow           = 0x52 ,
	NumLock           = 0x53 ,
	KeyPadSlah        = 0x54 ,
	KeyPadAsterisk    = 0x55 ,
	KeyPadMinus       = 0x56 ,
	KeyPadPlus        = 0x57 ,
	KeyPadEnter       = 0x58 ,
	KeyPadN1          = 0x59 ,
	KeyPadN2          = 0x5A ,
	KeyPadN3          = 0x5B ,
	KeyPadN4          = 0x5C ,
	KeyPadN5          = 0x5D ,
	KeyPadN6          = 0x5E ,
	KeyPadN7          = 0x5F ,
	KeyPadN8          = 0x60 ,
	KeyPadN9          = 0x61 ,
	KeyPadN0          = 0x62 ,
	KeyPadPoint       = 0x63 ,
	KeyPadBackSlash   = 0x64 ,
	KeyPadApp         = 0x65 ,
	KeyPadPower       = 0x66 ,
	KeyPadEqual       = 0x67 ,
	F13               = 0x68 ,
	F14               = 0x69 ,
	F15               = 0x6A ,
	F16               = 0x6B ,
	F17               = 0x6C ,
	F18               = 0x6D ,
	F19               = 0x6E ,
	F20               = 0x6F ,
	F21               = 0x70 ,
	F22               = 0x71 ,
	F23               = 0x72 ,
	F24               = 0x73 ,
	Excute            = 0x74 ,
	Help              = 0x75 ,
	Menu              = 0x76 ,
	Select            = 0x77 ,
	Stop              = 0x78 ,
	Again             = 0x79 ,
	Undo              = 0x7A ,
	Cut               = 0x7B ,
	Copy              = 0x7C ,
	Paste             = 0x7D ,
	Find              = 0x7E ,
	Mute              = 0x7F ,
	VolumeUp          = 0x80 ,
	VolumeDown        = 0x81 ,
	LockingCapsLock   = 0x82 ,
	LockingNumLock    = 0x83 ,
	LockingScrollLock = 0x84 ,
	KeyPadComma       = 0x85 ,
	KeyPadEqualSign   = 0x86 ,
	International1    = 0x87 ,
	International2    = 0x88 ,
	International3    = 0x89 ,
	International4    = 0x8A ,
	International5    = 0x8B ,
	International6    = 0x8C ,
	International7    = 0x8D ,
	International8    = 0x8E ,
	International9    = 0x8F ,
	Lang1             = 0x90 ,
	Lang2             = 0x91 ,
	Lang3             = 0x92 ,
	Lang4             = 0x93 ,
	Lang5             = 0x94 ,
	Lang6             = 0x95 ,
	Lang7             = 0x96 ,
	Lang8             = 0x97 ,
	Lang9             = 0x98 ,
	AltermateErase    = 0x99 ,
	SysReq_Attention  = 0x9A ,
	Cancel            = 0x9B ,
	Clear             = 0x9C ,
	Prior             = 0x9D ,
	Return            = 0x9E ,
	Separator         = 0x9F ,
	Out               = 0xA0 ,
	Oper              = 0xA1 ,
	ClearAgain        = 0xA2 ,
	CrSelPropo        = 0xA3 ,
	ExSel             = 0xA4 ,

	Keypad00          = 0xB0 ,
	KeyPad000         = 0xB1 ,
	ThousandsSep      = 0xB2 ,
	DecimalSep        = 0xB3 ,
	CurrencyUnit      = 0xB4 ,
	CurrencySubUnit   = 0xB5 ,
	KeyPadRLeftBra    = 0xB6 , // (
	KeyPadRRightBra   = 0xB7 , // )
	KeyPadBLeftBra    = 0xB8 , // {
	KeyPadBRightBra   = 0xB9 , // }
	KeyPadTab         = 0xBA ,
	KeyPadBackSpace   = 0xBB ,
	KeyPadA           = 0xBC ,
	KeyPadB           = 0xBD ,
	KeyPadC           = 0xBE ,
	KeyPadD           = 0xBF ,
	KeyPadE           = 0xC0 ,
	KeyPadF           = 0xC1 ,
	KeyPadXOR         = 0xC2 ,
	KeyPadCaret       = 0xC3 , // ^
	KeyPadPercentSign = 0xC4 , // %
	KeyPadLessThan    = 0xC5 , // <
	KeyPadGreaterThan = 0xC6 , // >
	KeyPadAmpersand   = 0xC7 , // &
	KeyPadDAmpersand  = 0xC8 , // && double ampersand
	KeyPadBar         = 0xC9 , // |
	KeyPadDBar        = 0xCA , // || double bar
	KeyPadColon       = 0xCB ,
	KeyPadSharp       = 0xCC ,
	KeyPadSpace       = 0xCD ,
	KeyPadAt          = 0xCE , // @
	KeyPadExclamation = 0xCF , // !
	KeyPadMemStore    = 0xD0 ,
	KeyPadMemRecall   = 0xD1 ,
	KeyPadMemClear    = 0xD2 ,
	KeyPadMemAdd      = 0xD3 ,
	KeyPadMemSubtract = 0xD4 ,
	KeyPadMemMultiply = 0xD5 ,
	KeyPadMemDivide   = 0xD6 ,
	KeyPadPlusMinux   = 0xD7 , // +/-
	KeyPadClear       = 0xD8 ,
	KeyPadClearEntry  = 0xD9 ,
	KeyPadBinary      = 0xDA ,
	KeyPadOctal       = 0xDB ,
	KeyPadDecimal     = 0xDC ,
	KeyPadHexadecimal = 0xDD ,

	LeftCONTROL       = 0xE0 ,
	LeftSHIFT         = 0xE1 ,
	LeftALT           = 0xE2 ,
	LeftGUI           = 0xE3 ,
	RightCONTROL      = 0xE4 ,
	RightSHIFT        = 0xE5 ,
	RightALT          = 0xE6 ,
	RightGUI          = 0xE7 ,

} ; // enum class KeyPage

} // namespace DekstopProfile

namespace ConsumerProfile
{

enum class KeyPage : uint16_t
{
	None                                   = 0x0000 ,
	ConsumerControl                        = 0x0001 ,
	NumericKeyPad                          = 0x0002 ,
	ProgrammableButtons                    = 0x0003 ,
	Microphone                             = 0x0004 ,
	HeadPhone                              = 0x0005 ,
	GraphicEqualizer                       = 0x0006 ,

	Plus10                                 = 0x0020 ,
	Plus100                                = 0x0021 ,
	AM_PM                                  = 0x0022 ,
	Power                                  = 0x0030 ,
	Reset                                  = 0x0031 ,
	Sleep                                  = 0x0032 ,
	SleepAfter                             = 0x0033 ,
	SleepMode                              = 0x0034 ,
	Illumination                           = 0x0035 ,
	FunctionButtons                        = 0x0036 ,

	Menu                                   = 0x0040 ,
	MenuPick                               = 0x0041 ,
	MenuUp                                 = 0x0042 ,
	MenuDown                               = 0x0043 ,
	MenuLeft                               = 0x0044 ,
	MenuRight                              = 0x0045 ,
	MenuEscape                             = 0x0046 ,
	MenuValueIncrease                      = 0x0047 ,
	MenuValueDecrease                      = 0x0048 ,

	DataOnScreen                           = 0x0060 ,
	ClosedCaption                          = 0x0061 ,
	ClosedCaptionSelect                    = 0x0062 ,
	VCR_TV                                 = 0x0063 ,
	BroadcastMode                          = 0x0064 ,
	Snapshot                               = 0x0065 ,
	Still                                  = 0x0066 ,
	Picture_in_Picture_Toggle              = 0x0067 ,
	Pciture_in_Picture_Swap                = 0x0068 ,

	RedMenuButton                          = 0x0069 ,
	GreenMenuButton                        = 0x006A ,
	BlueMenuButton                         = 0x006B ,
	YellowMenuButton                       = 0x006C ,

	Aspect                                 = 0x006D ,
	ThreeDModeSelect                       = 0x006E ,

	DisplayBrightnessIncrement             = 0x006F ,
	DisplayBrightnessDecrement             = 0x0070 ,
	DisplayBritness                        = 0x0071 ,
	DisplayBacklightToggle                 = 0x0072 ,
	DisplaySetBrightnessToMinimum          = 0x0073 ,
	DisplaySetBrightnessToMaximum          = 0x0074 ,
	DisplaySetAutoBrightness               = 0x0075 ,

	CameraAccessEnabled                    = 0x0076 ,
	CameraAccessDisabled                   = 0x0077 ,
	CameraAccessToggle                     = 0x0078 ,

	KeyboardBrightnessIncrement            = 0x0079 ,
	KeyboardBrightnessDecrement            = 0x007A ,
	KeyboardBacklightSetLevel              = 0x007B ,
	KeyboardBacklightOOC                   = 0x007C ,
	KeyboardBacklightSetMinimum            = 0x007D ,
	KeyboardBacklightSetMaximum            = 0x007E ,
	KeyboardBacklightAuto                  = 0x007F ,

	Selection                              = 0x0080 ,
	AssignSelection                        = 0x0081 ,
	ModeStep                               = 0x0082 ,
	RecallLast                             = 0x0083 ,
	EnterChannel                           = 0x0084 ,
	OrderMovie                             = 0x0085 ,
	Channel                                = 0x0086 ,

	MediaSelection                         = 0x0087 ,
	MediaSelectComputer                    = 0x0088 ,
	MediaSelectTV                          = 0x0089 ,
	MediaSelectWWW                         = 0x008A ,
	MediaSelectDVD                         = 0x008B ,
	MediaSelectTelephone                   = 0x008C ,
	MediaSelectProgramGuide                = 0x008D ,
	MediaSelectVideoPhone                  = 0x008E ,
	MediaSelectGames                       = 0x008F ,
	MediaSelectMessages                    = 0x0090 ,
	MediaSelectCD                          = 0x0091 ,
	MediaSelectVCR                         = 0x0092 ,
	MediaSelectTuner                       = 0x0093 ,
	Quit                                   = 0x0094 ,
	Help                                   = 0x0095 ,
	MediaSelectTape                        = 0x0096 ,
	MediaSelectCable                       = 0x0097 ,
	MediaSelectSatellite                   = 0x0098 ,
	MediaSelectSecurity                    = 0x0099 ,
	MediaSelectHome                        = 0x009A ,
	MediaSelectCall                        = 0x009B ,
	ChannelIncrement                       = 0x009C ,
	ChannelDecrement                       = 0x009D ,
	MediaSelectSAP                         = 0x009E ,

	VCRPlus                                = 0x00A0 ,
	Once                                   = 0x00A1 ,
	Daily                                  = 0x00A2 ,
	Weekly                                 = 0x00A3 ,
	Monthly                                = 0x00A4 ,

	Play                                   = 0x00B0 ,
	Pause                                  = 0x00B1 ,
	Record                                 = 0x00B2 ,
	FastForward                            = 0x00B3 ,
	Rewind                                 = 0x00B4 ,
	ScanNextTrack                          = 0x00B5 ,
	ScanPreviousTrack                      = 0x00B6 ,
	Stop                                   = 0x00B7 ,
	Eject                                  = 0x00B8 ,
	RandomPlay                             = 0x00B9 ,

	SelectDisc                             = 0x00BA ,
	EnterDisc                              = 0x00BB ,
	Repeat                                 = 0x00BC ,
	Tracking                               = 0x00BD ,
	TrackNormal                            = 0x00BE ,
	SlowTracking                           = 0x00BF ,

	FrameForward                           = 0x00C0 ,
	FrameBack                              = 0x00C1 ,
	Mark                                   = 0x00C2 ,
	ClearMark                              = 0x00C3 ,
	RepeatFromMark                         = 0x00C4 ,
	ReturnToMark                           = 0x00C5 ,
	SearchMarkForward                      = 0x00C6 ,
	SearchMarkBackwards                    = 0x00C7 ,
	CounterReset                           = 0x00C8 ,
	ShowCounter                            = 0x00C9 ,
	TrackingIncrement                      = 0x00CA ,
	TrackingDecrement                      = 0x00CB ,
	Stop_Eject                             = 0x00CC ,
	Play_Pause                             = 0x00CD ,
	Play_Skip                              = 0x00CE ,
	VoiceControl                           = 0x00CF ,

	InvokeCaptureInterface                 = 0x00D0 ,
	StartOrStopGameRecording               = 0x00D1 ,
	HistoricalGameCapture                  = 0x00D2 ,
	CaptureGameScreenshot                  = 0x00D3 ,
	ShowOrHideRecordingIndicator           = 0x00D4 ,
	StartOrStopMicrophoneCapture           = 0x00D5 ,
	StartOrStopCameraCapture               = 0x00D6 ,
	StartOrStopGameBroadcast               = 0x00D7 ,
	StartOrStopVoiceDictationSession       = 0x00D8 ,
	Invoke_DismissEmojiPicker              = 0x00D9 ,

	Volume                                 = 0x00E0 ,
	Balance                                = 0x00E1 ,
	Mute                                   = 0x00E2 ,
	Bass                                   = 0x00E3 ,
	Treble                                 = 0x00E4 ,
	BassBoost                              = 0x00E5 ,
	SurroundMode                           = 0x00E6 ,
	Loudness                               = 0x00E7 ,
	MPX                                    = 0x00E8 ,
	VolumeIncrement                        = 0x00E9 ,
	VolumeDecrement                        = 0x00EA ,

	SpeedSelect                            = 0x00F0 ,
	PlaybackSpeed                          = 0x00F1 ,
	StandardPlay                           = 0x00F2 ,
	LongPlay                               = 0x00F3 ,
	ExtendedPlay                           = 0x00F4 ,
	Slow                                   = 0x00F5 ,

	FanEanble                              = 0x0100 ,
	FanSpeed                               = 0x0101 ,
	LightEnable                            = 0x0102 ,
	LightIlluminationLevel                 = 0x0103 ,
	ClimateControlEnable                   = 0x0104 ,
	RoomTemperature                        = 0x0105 ,
	SecurityEnable                         = 0x0106 ,
	FireAlarm                              = 0x0107 ,
	PoliceAlarm                            = 0x0108 ,
	Proximity                              = 0x0109 ,
	Motion                                 = 0x010A ,
	DuressAlarm                            = 0x010B ,
	HoldupAlarm                            = 0x010C ,
	MedicalAlarm                           = 0x010D ,

	BalanceRight                           = 0x0150 ,
	BalanceLeft                            = 0x0151 ,
	BassIncrement                          = 0x0152 ,
	BassDecrement                          = 0x0153 ,
	TrebleIncrement                        = 0x0154 ,
	TrebleDecrement                        = 0x0155 ,

	SpeakerSystem                          = 0x0160 ,
	ChannelLeft                            = 0x0161 ,
	ChannelRight                           = 0x0162 ,
	ChannelCenter                          = 0x0163 ,
	ChannelFront                           = 0x0164 ,
	ChannelCenterFront                     = 0x0165 ,
	ChannelSide                            = 0x0166 ,
	ChannelSurround                        = 0x0167 ,
	ChannelLowFrequencyEnhancement         = 0x0168 ,
	ChannelTop                             = 0x0169 ,
	ChannelUnknown                         = 0x016A ,

	// ...
	// ...

	ExtendedKeyboardAttributesCollection   = 0x02C0 ,
	KeyboardFormFactor                     = 0x02C1 ,
	KeyboardKeyType                        = 0x02C2 ,
	KeyboardPhysicalLayout                 = 0x02C3 ,
	VendorSpecificKeyboardPhysicalLayout   = 0x02C4 ,
	KeyboardIETFLanguageTagIndex           = 0x02C5 ,
	ImplementedKeyboardInputAssistControl  = 0x02C6 ,
	KeyboardInputAssistPrevious            = 0x02C7 ,
	KeyboardInputAssistNext                = 0x02C8 ,
	KeyboardInputAssistPreviousGroup       = 0x02C9 ,
	KeyboardInputAssistNextGroup           = 0x02CA ,
	KeyboardInputAssistAccept              = 0x02CB ,
	KeyboardInputAssistCancel              = 0x02CC ,

	PrivacyScreenToggle                    = 0x02D0 ,
	PrivacyScreenLevelDecrement            = 0x02D1 ,
	PrivacyScreenLevelIncrement            = 0x02D2 ,
	PrivacyScreenLevelMinimum              = 0x02D3 ,
	PrivacyScreenLevelMaximum              = 0x02D4 ,

	ContactEdited                          = 0x0500 ,
	ContactAdded                           = 0x0501 ,
	ContactRecordActive                    = 0x0502 ,
	ContactIndex                           = 0x0503 ,
	ContactNickname                        = 0x0504 ,
	ContactFirstName                       = 0x0505 ,
	ContactLastName                        = 0x0506 ,
	ContactFullName                        = 0x0507 ,
	ContactPhoneNumberPersonal             = 0x0508 ,
	ContactPhoneNumberBusiness             = 0x0509 ,
	ContactPhoneNumberMobile               = 0x050A ,
	ContactPhoneNumberPager                = 0x050B ,
	ContactPhoneNumberFax                  = 0x050C ,
	ContactPhoneNumberOther                = 0x050D ,
	ContactEmailPersonal                   = 0x050E ,
	ContactEmailBusiness                   = 0x050F ,
	ContactEmailOther                      = 0x0510 ,
	ContactEmailMain                       = 0x0511 ,
	ContactSpeedDialNumber                 = 0x0512 ,
	ContactStatusFlag                      = 0x0513 ,
	ContactMisc                            = 0x0514 ,


} ; // enum class KeyPage

} // namespace ConsumerProfile

} // namespace HID

} // namespace daniel

